### PR TITLE
Solves #4: Added more periods and proper attribution.

### PR DESCRIPTION
**Pull request by graypegg**
Solves issue #4. Attribution added for issue commenters.

ping @valeriahacks

### CODE REVIEW

**Comment by valeriahacks** [comment]
lgtm @graypegg

**Comment by graypegg** [comment]
lgtm @valeriahacks

**Comment by valeriahacks** [comment]
@graypegg you illiterate wanker - why are the "and"s capitalized?

**Comment by graypegg** [comment]
@HellooooNewman Should be good now, leaving the 'ands' in for clarity

**Pull request closed without merging**
